### ISSUE TITLE
Segmentation fault in qtm example

### ISSUE THREAD

**Issue by cnga** [gtcasl/qsim#37]
'qtm' example in qsim/examples/x86/ gives a segmentation fault at a pthread_cond_wait from Qemu code (qemu_cond_wait at qemu/util/qemu-thread-posix.c).

**Comment by pranith** [comment]
This is now fixed upstream. Thanks for reporting!

**Comment by cnga** [comment]
Thanks! I've tested it and it's indeed working when booting an image.
However, I still cannot get it to work with a "state file".
I generated state files with several CPUs with the qsim-fastforwarder tool and tried to use it with the  QTM example unsuccessfully. QTM crashes again in the same point reported above.
Should the state files be generated differently?

**Comment by cnga** [comment]
I just made it work with the statefile; I added a mutex lock every time a thread is advancing instructions in the OSDomain:
      pthread_mutex_lock(&running_mutex);
      arg->cd->run(arg->cpu, 1000000/BRS_PER_MILN);
      pthread_mutex_unlock(&running_mutex);

**Comment by pranith** [comment]
ok, can you please submit the patch as a pull request?

**Comment by pranith** [comment]
Fixed with commit be77c1a192c91be414e2b85dc1de3de5ae251bf1. Thanks for reporting.
